[package]
name = "airline-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
airline = { git = "ssh://git@github.com/jacksonzamorano/airline.git", version = "0.1.0" }
